### ISSUE TITLE
Upgrade Jenkins Ubuntu vms to Focal Fossa (20.04)

### ISSUE THREAD

**Issue by maelk** [metal3-io/project-infra#130]
In order to get the UEFI to work for metal3-dev-env in Ubuntu, we need a recent version of Libvirt that is in Focal, not in Xenial. So we should upgrade Ubuntu, to support this new feature

**Comment by fmuyassarov** [comment]
@maelk should this be closed since we have now switched to 20.04 as you said?

**Comment by maelk** [comment]
yes, this is fixed. thanks for the reminder.
/close
