### ISSUE TITLE
Set up RBAC so all metal3-io members can view test pods

### ISSUE THREAD

**Issue by russellb** [metal3-io/project-infra#17]
Right now only a small group has access to the CI cluster itself.  It would be nice to allow access to anyone in the metal3-io github org, at least with read-only access to the `test-pods` namespace to view the Pods for test jobs and to inspect their logs directly.

**Comment by stbenjam** [comment]
@russellb Is this still the case?

**Comment by russellb** [comment]
I still haven't done this.  It also hasn't come up as necessary.  We can probably just close this and add the few people that need access as needed.
