### ISSUE TITLE
Replace travis CI usage with prow jobs

### ISSUE THREAD

**Issue by russellb** [metal3-io/project-infra#18]
We have travis-ci running some jobs against baremetal-operator and cluster-api-provider-baremetal.  We should be able to replace those with prow jobs.

**Comment by russellb** [comment]
This will be completed in cluster-api-provider-baremetal as of https://github.com/metal3-io/cluster-api-provider-baremetal/pull/122

**Comment by stbenjam** [comment]
The mentioned PR is merged.

/close
