### ISSUE TITLE
Sync labels across repos

### ISSUE THREAD

**Issue by russellb** [metal3-io/project-infra#20]
@stbenjam proposed using label_sync to sync labels across repos here: #12 

My first try with it didn't work, so I proposed a revert (#19), so this issue is a reminder to come back and try to make it work later.

**Comment by stbenjam** [comment]
Ah ok, I was hoping it was straight forward. I'll try it in a dummy org and see if I can figure out how to get it working.

**Comment by russellb** [comment]
Sounds great.  Let me know what happens when you try it.

**Comment by russellb** [comment]
Fixed by #21
