### ISSUE TITLE
Upgrade OpenShift cluster to 4.2.X release

### ISSUE THREAD

**Issue by russellb** [metal3-io/project-infra#35]
The CI cluster is currently running a nightly prerelease of OpenShift 4.2.  Once 4.2 is officially released, we should upgrade the cluster to an official release.

**Comment by stbenjam** [comment]
@russellb 4.2 is released, is the CI cluster still running on a prerelease?

**Comment by russellb** [comment]
nope, it's on a current official 4.2 release now

/close
