### ISSUE TITLE
Migration to dynamic worker workflow

### ISSUE THREAD

**Issue by Sunnatillo** [metal3-io/project-infra#705]
We decided to use dynamic jenkins worker. 
Here the progress of the move. 

Done:
✅ clusterctl upgrade tests
✅ feature tests
✅ dev env integration tests
✅ e2e basic
✅ e2e_integration tests
✅ k8s_upgrade tests
✅ ephemeral tests
✅  bmo e2e
✅   fullstack build
✅   Nordix clone

Note! We are are also splitting pipelines for dev_env and e2e_tests, and for feature tests we have already seperate pipeline.

**Comment by mboukhalfa** [comment]
cc @adilGhaffarDev

**Comment by Sunnatillo** [comment]
#725 moves following tests to dynamic works:  
e2e integration
e2e basic
k8s upgrade tests
ephemeral

**Comment by Rozzii** [comment]
This is actually done and not stale we are using dynamic workflow for every relevant test AFAIK.
