### ISSUE TITLE
Split Prow config into multiple files

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/project-infra#713]
Prow config is thousands of lines, and hard to manage and read. Split it in the style of https://github.com/kubernetes/test-infra/tree/master/config/jobs

**Comment by tuminoid** [comment]
ping @lentzi90

**Comment by lentzi90** [comment]
/triage accepted
Thanks for creating the issue!

**Comment by NymanRobin** [comment]
/remove-lifecycle stale
Maybe branches that are not maintained anymore could be deleted in conjunction with this as otherwise the configs grow to infinity

**Comment by tuminoid** [comment]
> /remove-lifecycle stale Maybe branches that are not maintained anymore could be deleted in conjunction with this as otherwise the configs grow to infinity

We do remove branches that are not maintained from the config, but ever since moving from Jenkins jobs to Prow jobs, the config has so many permutations that it is better split for easier maintenance.
