### ISSUE TITLE
Separate node image building and testing

### ISSUE THREAD

**Issue by NymanRobin** [metal3-io/project-infra#826]
## The issue

Currently when looking at the node image building pipeline it can be seen that the building time of a image is extremely long ~1 hour per distribution. However when the building step in Jenkins is examined closer it actually contains both the building of image and testing of the image. To make the process more transparent and the error spotting easier separate the test and build steps.

However, currently the testing is part of the same script as the building so a small refactoring is needed here before a separate step can be added in Jenkins.

Jenkins job [periodic_node_image_building](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_periodic_node_image_building/)

**Comment by Rozzii** [comment]
I actually don't agree with this issue in its current from. The testing is done in a separate Jenkins build "stage" so although it is part of the same pipeline scrip you can actually filter out all the noise and just check the test related log output e.g. https://jenkins.nordix.org/blue/organizations/jenkins/metal3_periodic_node_image_building/detail/metal3_periodic_node_image_building/56/pipeline/95
/triage needs-information

**Comment by NymanRobin** [comment]
Yes this is because the issue is done in my opinion @Rozzii! When I submitted it there was only one stage. All in all I will close this now 😄
