### ISSUE TITLE
Discrepancy between Jenkins pipelines and Prow's Config

### ISSUE THREAD

**Issue by NymanRobin** [metal3-io/project-infra#837]
There is a discrepancy between Jenkins pipeline configs and the Prow config, the root cause of this was that the decision to only keep the latest upgrade for each branch. However, the Prow config was never updated to reflect this.

Further none of the configs for branch `release-1.7` does match the actual config that exists. We should check all the Prow configs and make them reflect the tests in Jenkins

**Comment by NymanRobin** [comment]
I think it is already dealt with in the PR #838 
But basically the names of the Prow triggers of the upgrade tests did not match the Jenkins pipeline jobs and thus no test were ran. Happened for example in this PR #776

**Comment by tuminoid** [comment]
Yeah the PR makes it clear now, thanks for the update and the fix.
