### ISSUE TITLE
Prow cluster autoscaler stuck occasionally

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/project-infra#881]
Due to this issue https://github.com/kubernetes/autoscaler/issues/6490#issuecomment-2076610573 the cluster autoscaler sometimes gets stuck in a loop where it thinks it doesn't have enough privileges to continue.
Deleting the pod gets it going again, but this depends on someone noticing it.

I propose that we either monitor the autoscaler every day to detect when it gets stuck OR we add the RBAC the controller thinks it needs until the upstream issue is fixed.

**Comment by tuminoid** [comment]
Unless the RBAC it thinks it needs is very invasive, I think that is better workaround than constant manual monitoring. If implemented with RBAC, let's make sure we have revert PR or issue for reverting the change available right after merge.

/triage accepted
